// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATUFDKRtCU5yfOCoF7nuc5lJ0bXuUr3tE',
    appId: '1:393815018834:android:e86302fdb67cae3f0ffe8b',
    messagingSenderId: '393815018834',
    projectId: 'tonase-asa-3392e',
    storageBucket: 'tonase-asa-3392e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXqgcJJs_sCDP3I1KPgev046GVrBR-xOE',
    appId: '1:393815018834:web:752729a1cfb70ae40ffe8b',
    messagingSenderId: '393815018834',
    projectId: 'tonase-asa-3392e',
    authDomain: 'tonase-asa-3392e.firebaseapp.com',
    storageBucket: 'tonase-asa-3392e.firebasestorage.app',
    measurementId: 'G-KGQHM6DZKR',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqgcJJs_sCDP3I1KPgev046GVrBR-xOE',
    appId: '1:393815018834:web:752729a1cfb70ae40ffe8b',
    messagingSenderId: '393815018834',
    projectId: 'tonase-asa-3392e',
    authDomain: 'tonase-asa-3392e.firebaseapp.com',
    storageBucket: 'tonase-asa-3392e.firebasestorage.app',
    measurementId: 'G-KGQHM6DZKR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZjCKzMKCEFLXvecHoy7IecsfsGV2gHjk',
    appId: '1:393815018834:ios:bc22e8af6edaf4180ffe8b',
    messagingSenderId: '393815018834',
    projectId: 'tonase-asa-3392e',
    storageBucket: 'tonase-asa-3392e.firebasestorage.app',
    iosBundleId: 'com.example.tonaseApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZjCKzMKCEFLXvecHoy7IecsfsGV2gHjk',
    appId: '1:393815018834:ios:bc22e8af6edaf4180ffe8b',
    messagingSenderId: '393815018834',
    projectId: 'tonase-asa-3392e',
    storageBucket: 'tonase-asa-3392e.firebasestorage.app',
    iosBundleId: 'com.example.tonaseApp',
  );

}